apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: frontend
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend
            port:
              number: 80
---
kind: Service 
apiVersion: v1 
metadata:
  name: frontend-np-service 
spec:
  type: NodePort
  selector:
    app: frontend

  ports:
    - nodePort: 30163
      port: 80
      targetPort: 8080